"""Write the filming plan: shot_list.csv (read by src.rename_recordings) and SHOT_LIST.md (to film from).

    python -m src.make_shot_list

Order: 5 pilot recordings; 72 main clips (8 angles x 9 takes, 3 per angle at each cross, angles
shuffled within 9 blocks, fixed seed); 18 transports (the cube carried to another cross, 12 without
and 6 with a turn); 16 optional fast turns. Crosses are named from the person's seat: A = their left,
B = middle, C = their right. Clip names keep the start cross; the end cross is in the list.
"""
import csv
import random

from src.common import ROOT

ANGLES = [-90, -60, -30, 0, 30, 60, 90, 120]
MOVES = [("A", "B"), ("B", "C"), ("A", "C"), ("C", "A"), ("B", "A"), ("C", "B")]


def plan():
    rows = [dict(name="pilot_static", angle="", start="A", end="A", block="pilot",
                 notes="5 s, nothing moves: cube on cross A, hand flat on the table beside it"),
            dict(name="pilot_signs", angle="", start="B", end="B", block="pilot",
                 notes="cube on B turned +90 four times on the table (hand out of view, 2 s still after each); "
                       "then hand flat, turned +90"),
            dict(name="clip_01_rot+60_A", angle=60, start="A", end="A", block="pilot", notes="pilot clip"),
            dict(name="clip_02_rot-90_B", angle=-90, start="B", end="B", block="pilot", notes="pilot clip"),
            dict(name="clip_03_rot+0_C", angle=0, start="C", end="C", block="pilot", notes="pilot clip")]
    n = 4

    def add(angle, start, end, block, notes=""):
        nonlocal n
        rows.append(dict(name=f"clip_{n:02d}_rot{angle:+d}_{start}", angle=angle, start=start, end=end,
                         block=block, notes=notes))
        n += 1

    rng = random.Random(7)
    for b in range(9):
        order = list(range(len(ANGLES)))
        rng.shuffle(order)
        for k in order:
            spot = "ABC"[(b + k) % 3]
            add(ANGLES[k], spot, spot, f"main {b + 1}")
    for rep in range(2):
        for start, end in MOVES:
            add(0, start, end, "transport", "carry without turning")
    for (start, end), angle in zip(MOVES, (60, -60, 90, -90, 30, -30)):
        add(angle, start, end, "transport", "carry and turn")
    for rep in range(2):
        for k, angle in enumerate(ANGLES):
            spot = "ABC"[(rep + k) % 3]
            add(angle, spot, spot, "fast (optional)", "fast turn, about 0.5 s instead of 1-2 s")
    for i, r in enumerate(rows, 1):
        r["order"] = i
    return rows


def turn_text(angle):
    if angle == "":
        return "-"
    return "0 (no turn)" if angle == 0 else f"{angle:+d} ({'counter-clockwise' if angle > 0 else 'clockwise'})"


def table(rows):
    lines = ["| ✓ | # | file name | turn (deg) | from | to |", "|---|---|---|---|---|---|"]
    for r in rows:
        to = r["end"] if r["end"] == r["start"] else f"**{r['end']}**"
        lines.append(f"| ☐ | {r['order']} | `{r['name']}` | {turn_text(r['angle'])} | {r['start']} | {to} |")
    return "\n".join(lines)


def markdown(rows):
    by = lambda b: [r for r in rows if r["block"] == b]
    main_blocks = "\n\n".join(f"**Block {b}**\n\n{table(by(f'main {b}'))}" for b in range(1, 10))
    return f"""# Shot list (6 Oct)

Generated by `python -m src.make_shot_list`. `shot_list.csv` holds the same list; `src.rename_recordings` names your
recordings from it, in order.

| Part | Recordings | Time |
|---|---|---|
| Pilot (then check) | 5 | ~10 min |
| Main set: 8 turn angles x 9 takes, 3 at each cross | 72 | ~60-75 min |
| Transports: the cube carried to another cross (12 without a turn, 6 with one) | 18 | ~15-20 min |
| Optional: fast turns | 16 | ~15 min |

## Set up once

- **Head aim:** aimed at the crosses (about 8 cm above them), with marker 13 low in the image. **Framing check:** hold the
  cube about 10 cm above each cross; the cube and your hand card must both be well inside the image, top included.
- **Recorder:** 30 fps, both cameras, short fixed exposure (no motion blur), fixed focus.
- **Markers:**
  - All flat, with their white margins visible.
  - Cube: marker 1 on top, middle layer taped so it cannot twist.
  - Hand card: its top edge toward your fingertips.
- **Light:** constant, no glare on the markers.
- **Crosses,** as you sit facing the robot: **A = your left, B = middle, C = your right**.

## Every clip, the same way (about 10 s)

1. **Start recording.** The cube rests on its cross and your hand is **out of view for at least 1 s**. Between clips, vary
   the cube's starting turn a little (marker 1 always on top).
2. **Side pinch:** thumb on the cube's **left face**, two fingers on its **right face**, palm raised. Keep the faces toward
   you and toward the robot free.
3. **Lift about 8 cm and turn** by the clip's angle while it is lifted.
   - The turn is **yaw only**, about the vertical axis: the cube stays upright, with no tipping.
   - **+ = counter-clockwise seen from above** (the way you open a jar lid); **- = clockwise**.
   - For 90 and 120 deg: turn your hand the opposite way *before* grasping, then rotate through.
4. **Put it down** on the **"to" cross**: the same cross, except in the transport block. The exact spot does not matter.
   Let go, move your hand **out of view for at least 1 s**, then stop recording.
5. **Bad take** (dropped, hand left the image, wrong angle, cube twisted)? **Delete both camera files of that recording
   straight away** and redo the same row, so the order stays right.

## Pilot: film these 5 first, then check

{table(by("pilot"))}

```bash
cd ~/Documents/"humanoid project"; unset PYTHONPATH; source ~/.venvs/robot-sim/bin/activate
python -m src.rename_recordings --recordings <recorder folder> --since <today, e.g. 20261006>          # check the mapping
python -m src.rename_recordings --recordings <recorder folder> --since <today, e.g. 20261006> --apply
python -m src.pilot_check static     # IDs, real marker sizes, head pose
python -m src.pilot_check signs      # cube 0/+90/+180/+270, hand 0/+90
python -m src.prepare_videos --data data/raw && python -m src.qc --data data/raw
```

**Go on** if:
- the IDs are right;
- the measured sizes are entered in `src/constants.py` (`TABLE_MARKER`, `WRIST_MARKER`);
- the signs are right;
- QC says OK with `held%` around 50 or more.

Otherwise send me the output.

## Main set: 72 clips

The rename command continues at the next unused name (it remembers what it already copied), so run it after each block
or at the end.

{main_blocks}

## Transports: 18 clips (the cube goes to another cross)

**Pick it up, carry it to the cross in bold, put it down.** Six of these also turn the cube on the way. The replay then
also tests how well your hand's movement, not only its turn, transfers to the robot. Tested on synthetic clips: a
27 cm carry from A to C landed within 1.3 cm.

{table(by("transport"))}

## Optional: 16 fast turns (about 0.5 s instead of 1-2 s)

These give the world model faster dynamics, where the cube might slip in your fingers. Film them only if there is time.

{table(by("fast (optional)"))}

## After filming

```bash
python -m src.rename_recordings --recordings <recorder folder> --since <today> --apply
python -m src.prepare_videos --data data/raw && python -m src.qc --data data/raw
python -m src.run_all --data data/raw --out outputs/real
```

- **QC says RESHOOT for a clip:** film it again, then
  `python -m src.rename_recordings --recordings <folder> --since <time of the retake> --names <clip name> --apply --overwrite`.
"""


def main():
    rows = plan()
    with open(ROOT / "shot_list.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["order", "name", "rotation_deg", "start_cross", "end_cross", "block", "notes"])
        w.writeheader()
        for r in rows:
            w.writerow(dict(order=r["order"], name=r["name"], rotation_deg=r["angle"], start_cross=r["start"],
                            end_cross=r["end"], block=r["block"], notes=r["notes"]))
    (ROOT / "SHOT_LIST.md").write_text(markdown(rows))
    counts = {b: sum(r["block"].startswith(b) for r in rows) for b in ("pilot", "main", "transport", "fast")}
    print(f"wrote shot_list.csv and SHOT_LIST.md: {len(rows)} recordings {counts}")


if __name__ == "__main__":
    main()
